server {
    listen 80;
    
    # Enable gzip compression for optimization
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Nginx Fallback to index.html to prevent 404s on refresh for client-side routing
        try_files $uri $uri/ /index.html;
    }
}
